BEGIN;

-- ==============================================================================
-- 1. tb_ob_workflow_master
-- ==============================================================================
INSERT INTO public.tb_ob_workflow_master (app_id, workflow_id, workflow_desc, workflow_status) VALUES
('APZCBO', 'CMKMINPUT',      'Customer Management - Kendra Manager (KM) Edit Flow',                 'ACTIVE'),
('APZCBO', 'CMDEOINPUT',     'Customer Management - Data Entry Operator (DEO) Edit Flow',           'ACTIVE'),
('APZCBO', 'CMBMINPUT',      'Customer Management - Branch Manager (BM) Edit & Review Flow',        'ACTIVE'),
('APZCBO', 'CMAMINPUT',      'Customer Management - Area Manager (AM) Edit & Review Flow',          'ACTIVE'),
('APZCBO', 'CMRPCMAKER',     'Customer Management - Regional Processing Center Maker Flow',         'ACTIVE'),
('APZCBO', 'CMRPCCHECKER',   'Customer Management - Regional Processing Center Checker Flow',       'ACTIVE'),
('APZCBO', 'CMSYSTEM',       'Customer Management - System STP, BRE & Core Banking Integration',   'ACTIVE'),
('APZCBO', 'CMAMLHO',        'Customer Management - Anti-Money Laundering Head Office Review',      'ACTIVE'),
('APZCBO', 'CMCRT',          'Customer Management - Credit Risk Team (CRT) Review Flow',            'ACTIVE'),
('APZCBO', 'CMINSURANCE',    'Customer Management - Insurance Team Review Flow',                    'ACTIVE'),
('APZCBO', 'CMCHT',          'Customer Management - Central Helpdesk Team (CHT) Retrigger Flow',    'ACTIVE'),
('APZCBO', 'CMRPCTL',        'Customer Management - RPC Team Leader Sample Verification',           'ACTIVE'),
('APZCBO', 'CMRPCHO',        'Customer Management - RPC Head Office Sample Verification',           'ACTIVE'),
('APZCBO', 'CMBST',          'Customer Management - Business Support Team (BST) Verification',      'ACTIVE');

-- ==============================================================================
-- 2. tb_ob_workflow_definition (All 64 Transitions from Matrix)
-- ==============================================================================
INSERT INTO public.tb_ob_workflow_definition ("action", app_id, from_stage_id, workflow_id, create_ts, curr_role, next_role, next_stage_id, next_workflow_status, present_role, remarks, rule_id, stage_seq_no) VALUES
  ('EDIT', 'APZCBO', 'INITIATE', 'CMKMINPUT', CURRENT_TIMESTAMP, 'KM', 'KM', 'DRAFT', 'DRAFT_CREATED', 'KM', 'KM clicks Edit/Modify Member Details on the Member Profile screen and starts the edit flow. A draft request is created (only one active request per customer).', NULL, 1),
  ('SAVE', 'APZCBO', 'DRAFT', 'CMKMINPUT', CURRENT_TIMESTAMP, 'KM', 'KM', 'DRAFT', 'DRAFT_SAVED', 'KM', 'KM saves the request. It stays in the Drafts queue.', NULL, 1),
  ('SUBMIT', 'APZCBO', 'DRAFT', 'CMKMINPUT', CURRENT_TIMESTAMP, 'KM', 'BM', 'BMQUEUE', 'BMQUEUE_SUBMITTED', 'KM', 'KM edits one or more KYC fields and submits (non-STP). Request moves to Pending for BM Review.', NULL, 2),
  ('STPSUBMIT', 'APZCBO', 'DRAFT', 'CMKMINPUT', CURRENT_TIMESTAMP, 'KM', 'SYSTEM', 'STPSUBMITTED', 'STP_SUBMITTED', 'KM', 'KM submits without editing any KYC field (STP). The request bypasses BM/AM/RPC; request moves to AML (optional) and BRE.', NULL, 3),
  ('REJECT', 'APZCBO', 'DRAFT', 'CMKMINPUT', CURRENT_TIMESTAMP, 'KM', 'KM', 'DRAFTREJECTED', 'DRAFT_REJECTED', 'KM', 'Request rejected in Draft by KM (for example, the customer declines OTP consent or a dedupe match is found during capture).', NULL, 4),
  ('SUBMIT', 'APZCBO', 'BMONHOLD', 'CMKMINPUT', CURRENT_TIMESTAMP, 'KM', 'BM', 'BMQUEUE', 'BM_QUEUE_RESUBMIT', 'KM', 'KM resolves the queries raised by BM and resubmits. Request returns to Pending for BM Review.', NULL, 1),
  ('SUBMIT', 'APZCBO', 'RPCONHOLD', 'CMKMINPUT', CURRENT_TIMESTAMP, 'KM', 'RPC', 'RPCMAKERQUEUE', 'RPC_REWORK', 'KM', 'KM resolves the RPC queries and resubmits. Request moves to the RPC Maker Rework queue.', NULL, 1),
  ('EDIT', 'APZCBO', 'INITIATE', 'CMDEOINPUT', CURRENT_TIMESTAMP, 'DEO', 'DEO', 'DRAFT', 'DRAFT_CREATED', 'DEO', 'DEO clicks Edit/Modify Member Details on the Member Profile screen and starts the edit flow. A draft request is created (only one active request per customer).', NULL, 1),
  ('SAVE', 'APZCBO', 'DRAFT', 'CMDEOINPUT', CURRENT_TIMESTAMP, 'DEO', 'DEO', 'DRAFT', 'DRAFT_SAVED', 'DEO', 'DEO saves the request. It stays in the Drafts queue.', NULL, 1),
  ('SUBMIT', 'APZCBO', 'DRAFT', 'CMDEOINPUT', CURRENT_TIMESTAMP, 'DEO', 'BM', 'BMQUEUE', 'BMQUEUE_SUBMITTED', 'DEO', 'DEO edits one or more KYC fields and submits (non-STP). Request moves to Pending for BM Review.', NULL, 2),
  ('STPSUBMIT', 'APZCBO', 'DRAFT', 'CMDEOINPUT', CURRENT_TIMESTAMP, 'DEO', 'SYSTEM', 'STPSUBMITTED', 'STP_SUBMITTED', 'DEO', 'DEO submits without editing any KYC field (STP). The request bypasses BM/AM/RPC; request moves to AML (optional) and BRE.', NULL, 3),
  ('REJECT', 'APZCBO', 'DRAFT', 'CMDEOINPUT', CURRENT_TIMESTAMP, 'DEO', 'DEO', 'DRAFTREJECTED', 'DRAFT_REJECTED', 'DEO', 'Request rejected in Draft by DEO (for example, the customer declines OTP consent or a dedupe match is found during capture).', NULL, 4),
  ('SUBMIT', 'APZCBO', 'BMONHOLD', 'CMDEOINPUT', CURRENT_TIMESTAMP, 'DEO', 'BM', 'BMQUEUE', 'BM_QUEUE_RESUBMIT', 'DEO', 'DEO resolves the queries raised by BM and resubmits. Request returns to Pending for BM Review.', NULL, 1),
  ('SUBMIT', 'APZCBO', 'RPCONHOLD', 'CMDEOINPUT', CURRENT_TIMESTAMP, 'DEO', 'RPC', 'RPCMAKERQUEUE', 'RPC_REWORK', 'DEO', 'DEO resolves the RPC queries and resubmits. Request moves to the RPC Maker Rework queue.', NULL, 1),
  ('EDIT', 'APZCBO', 'INITIATE', 'CMBMINPUT', CURRENT_TIMESTAMP, 'BM', 'BM', 'DRAFT', 'DRAFT_CREATED', 'BM', 'BM clicks Edit/Modify Member Details on the Member Profile screen and starts the edit flow. A draft request is created (only one active request per customer).', NULL, 1),
  ('SAVE', 'APZCBO', 'DRAFT', 'CMBMINPUT', CURRENT_TIMESTAMP, 'BM', 'BM', 'DRAFT', 'DRAFT_SAVED', 'BM', 'BM saves the request. It stays in the Drafts queue.', NULL, 1),
  ('SUBMIT', 'APZCBO', 'DRAFT', 'CMBMINPUT', CURRENT_TIMESTAMP, 'BM', 'AM', 'AMQUEUE', 'AMQUEUE_SUBMITTED', 'BM', 'BM-initiated request with KYC fields edited (non-STP). The AM is the reviewer; request moves to Pending for AM Review.', NULL, 2),
  ('STPSUBMIT', 'APZCBO', 'DRAFT', 'CMBMINPUT', CURRENT_TIMESTAMP, 'BM', 'SYSTEM', 'STPSUBMITTED', 'STP_SUBMITTED', 'BM', 'BM submits without editing any KYC field (STP). The request bypasses BM/AM/RPC; request moves to AML (optional) and BRE.', NULL, 3),
  ('REJECT', 'APZCBO', 'DRAFT', 'CMBMINPUT', CURRENT_TIMESTAMP, 'BM', 'BM', 'DRAFTREJECTED', 'DRAFT_REJECTED', 'BM', 'Request rejected in Draft by BM (for example, the customer declines OTP consent or a dedupe match is found during capture).', NULL, 4),
  ('APPROVED', 'APZCBO', 'BMQUEUE', 'CMBMINPUT', CURRENT_TIMESTAMP, 'BM', 'RPC', 'RPCMAKERQUEUE', 'BM_APPROVED', 'BM', 'BM approves the KM/DEO request. Request moves to the RPC Maker''s Pool (New).', NULL, 1),
  ('PUSHBACK', 'APZCBO', 'BMQUEUE', 'CMBMINPUT', CURRENT_TIMESTAMP, 'BM', 'KM', 'BMONHOLD', 'BM_PUSHBACK', 'BM', 'BM pushes back with section-wise query reasons. Request moves to Onhold (From BM) for KM/DEO action.', NULL, 2),
  ('REJECT', 'APZCBO', 'BMQUEUE', 'CMBMINPUT', CURRENT_TIMESTAMP, 'BM', 'BM', 'BMREJECTED', 'BM_REJECTED', 'BM', 'BM rejects with a reason and remarks. Updation stops and the member keeps the old details. Request moves to the Rejected queue.', NULL, 3),
  ('SUBMIT', 'APZCBO', 'AMONHOLD', 'CMBMINPUT', CURRENT_TIMESTAMP, 'BM', 'AM', 'AMQUEUE', 'AM_QUEUE_RESUBMIT', 'BM', 'BM resolves the queries raised by AM and resubmits. Request returns to Pending for AM Review.', NULL, 1),
  ('SUBMIT', 'APZCBO', 'RPCONHOLD', 'CMBMINPUT', CURRENT_TIMESTAMP, 'BM', 'RPC', 'RPCMAKERQUEUE', 'RPC_REWORK', 'BM', 'BM resolves the RPC queries and resubmits. Request moves to the RPC Maker Rework queue.', NULL, 1),
  ('EDIT', 'APZCBO', 'INITIATE', 'CMAMINPUT', CURRENT_TIMESTAMP, 'AM', 'AM', 'DRAFT', 'DRAFT_CREATED', 'AM', 'AM clicks Edit/Modify Member Details on the Member Profile screen and starts the edit flow. A draft request is created (only one active request per customer).', NULL, 1),
  ('SAVE', 'APZCBO', 'DRAFT', 'CMAMINPUT', CURRENT_TIMESTAMP, 'AM', 'AM', 'DRAFT', 'DRAFT_SAVED', 'AM', 'AM saves the request. It stays in the Drafts queue.', NULL, 1),
  ('SUBMIT', 'APZCBO', 'DRAFT', 'CMAMINPUT', CURRENT_TIMESTAMP, 'AM', 'RPC', 'RPCMAKERQUEUE', 'RPC_QUEUE', 'AM', 'AM-initiated request with KYC fields edited (non-STP). No BM review; request goes directly to the RPC Maker''s Pool.', NULL, 2),
  ('STPSUBMIT', 'APZCBO', 'DRAFT', 'CMAMINPUT', CURRENT_TIMESTAMP, 'AM', 'SYSTEM', 'STPSUBMITTED', 'STP_SUBMITTED', 'AM', 'AM submits without editing any KYC field (STP). The request bypasses BM/AM/RPC; request moves to AML (optional) and BRE.', NULL, 3),
  ('REJECT', 'APZCBO', 'DRAFT', 'CMAMINPUT', CURRENT_TIMESTAMP, 'AM', 'AM', 'DRAFTREJECTED', 'DRAFT_REJECTED', 'AM', 'Request rejected in Draft by AM (for example, the customer declines OTP consent or a dedupe match is found during capture).', NULL, 4),
  ('APPROVED', 'APZCBO', 'AMQUEUE', 'CMAMINPUT', CURRENT_TIMESTAMP, 'AM', 'RPC', 'RPCMAKERQUEUE', 'AM_APPROVED', 'AM', 'AM approves the BM-initiated request. Request moves to the RPC Maker''s Pool (New).', NULL, 1),
  ('PUSHBACK', 'APZCBO', 'AMQUEUE', 'CMAMINPUT', CURRENT_TIMESTAMP, 'AM', 'BM', 'AMONHOLD', 'AM_PUSHBACK', 'AM', 'AM pushes back with section-wise query reasons. Request moves to Onhold (From AM) for BM action.', NULL, 2),
  ('REJECT', 'APZCBO', 'AMQUEUE', 'CMAMINPUT', CURRENT_TIMESTAMP, 'AM', 'AM', 'AMREJECTED', 'AM_REJECTED', 'AM', 'AM rejects with a reason and remarks. Request moves to the Rejected queue.', NULL, 3),
  ('SUBMIT', 'APZCBO', 'RPCONHOLD', 'CMAMINPUT', CURRENT_TIMESTAMP, 'AM', 'RPC', 'RPCMAKERQUEUE', 'RPC_REWORK', 'AM', 'AM (AM-initiated request) resolves the RPC queries and resubmits. Request moves to the RPC Maker Rework queue.', NULL, 1),
  ('APPROVED', 'APZCBO', 'RPCMAKERQUEUE', 'CMRPCMAKER', CURRENT_TIMESTAMP, 'RPCMAKER', 'SYSTEM', 'RPCAPPROVED', 'RPC_MAKER_APPROVED', 'RPCMAKER', 'RPC Maker submits without editing (single-level verification). Request moves to RPC Approved (AML optional, then BRE).', NULL, 1),
  ('CHECKER', 'APZCBO', 'RPCMAKERQUEUE', 'CMRPCMAKER', CURRENT_TIMESTAMP, 'RPCMAKER', 'RPCCHECKER', 'RPCCHECKERQUEUE', 'RPC_CHECKER_QUEUE', 'RPCMAKER', 'RPC Maker edited one or more fields and submits. Request moves to the Checker''s Pool (a different user must review).', NULL, 2),
  ('ONHOLD', 'APZCBO', 'RPCMAKERQUEUE', 'CMRPCMAKER', CURRENT_TIMESTAMP, 'RPCMAKER', 'KM', 'RPCONHOLD', 'RPC_ONHOLD', 'RPCMAKER', 'RPC Maker raises section-wise queries and puts the request On Hold (From RPC). RPC cannot reject; On Hold is the only negative action.', NULL, 3),
  ('RESPOND', 'APZCBO', 'RPCONHOLD', 'CMRPCMAKER', CURRENT_TIMESTAMP, 'RPCMAKER', 'RPCCHECKER', 'RPCCHECKERQUEUE', 'RPC_ONHOLD_CLEARED', 'RPCMAKER', 'RPC Maker clears the on-hold queries and responds. Request moves to the Checker''s Pool.', NULL, 1),
  ('APPROVED', 'APZCBO', 'RPCCHECKERQUEUE', 'CMRPCCHECKER', CURRENT_TIMESTAMP, 'RPCCHECKER', 'SYSTEM', 'RPCAPPROVED', 'RPC_CHECKER_APPROVED', 'RPCCHECKER', 'RPC Checker approves (the Checker''s edits are final). Request moves to RPC Approved (AML optional, then BRE).', NULL, 1),
  ('ONHOLD', 'APZCBO', 'RPCCHECKERQUEUE', 'CMRPCCHECKER', CURRENT_TIMESTAMP, 'RPCCHECKER', 'KM', 'RPCONHOLD', 'RPC_ONHOLD', 'RPCCHECKER', 'RPC Checker raises queries and puts the request On Hold (From RPC). RPC cannot reject.', NULL, 2),
  ('RESPOND', 'APZCBO', 'RPCONHOLD', 'CMRPCCHECKER', CURRENT_TIMESTAMP, 'RPCCHECKER', 'RPCCHECKER', 'RPCCHECKERQUEUE', 'RPC_ONHOLD_CLEARED', 'RPCCHECKER', 'RPC Checker clears the on-hold queries and responds. Request returns to the Checker''s Pool for review by a different user.', NULL, 1),
  ('AML', 'APZCBO', 'RPCAPPROVED', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'AMLHO', 'AMLQUEUE', 'AML_QUEUE', 'SYSTEM', 'Post RPC approval: AML check is required (AML-trigger fields changed). Request moves to the AML queue for AML HO.', NULL, 1),
  ('BRE', 'APZCBO', 'RPCAPPROVED', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'BREQUEUE', 'BRE_QUEUE', 'SYSTEM', 'Post RPC approval: AML is not required (AML is optional). Request moves directly to the BRE queue.', NULL, 2),
  ('AML', 'APZCBO', 'STPSUBMITTED', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'AMLHO', 'AMLQUEUE', 'AML_QUEUE', 'SYSTEM', 'STP submit: AML check is required (AML-trigger fields changed). Request moves to the AML queue for AML HO.', NULL, 1),
  ('BRE', 'APZCBO', 'STPSUBMITTED', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'BREQUEUE', 'BRE_QUEUE', 'SYSTEM', 'STP submit: AML is not required (AML is optional). Request moves directly to the BRE queue.', NULL, 2),
  ('APPROVED', 'APZCBO', 'AMLQUEUE', 'CMAMLHO', CURRENT_TIMESTAMP, 'AMLHO', 'SYSTEM', 'BREQUEUE', 'AML_SUCCESS', 'AMLHO', 'AML HO clears the case (AML pass). Request moves to the BRE queue.', NULL, 1),
  ('REJECT', 'APZCBO', 'AMLQUEUE', 'CMAMLHO', CURRENT_TIMESTAMP, 'AMLHO', 'AMLHO', 'AMLREJECT', 'AML_REJECTED', 'AMLHO', 'AML HO rejects the case. Member is tagged as an AML hit and the request moves to AML Reject.', NULL, 2),
  ('PASS', 'APZCBO', 'BREQUEUE', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'T24UPDATE', 'BRE_SUCCESS', 'SYSTEM', 'BRE/CB API success. Request moves to T24 updation.', NULL, 1),
  ('INSURANCE', 'APZCBO', 'BREQUEUE', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'INSURANCE', 'INSQUEUE', 'INSURANCE_QUEUE', 'SYSTEM', 'BRE success and the marital status changed from Widowed to Married. Request moves to Insurance Team Review (configurable).', NULL, 2),
  ('FAIL', 'APZCBO', 'BREQUEUE', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'CRT', 'CRTQUEUE', 'CB_FAIL_PENDING', 'SYSTEM', 'BRE final decision is FAILURE (CB fail). Request moves to the CRT queue.', NULL, 3),
  ('QUEUE', 'APZCBO', 'BREQUEUE', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'BREQUEUE', 'BRE_RETRY', 'SYSTEM', 'BRE API down or no response (status unknown). Request stays in the BRE queue for scheduler retry.', NULL, 4),
  ('NEXT', 'APZCBO', 'T24UPDATE', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'COMPLETED', 'T24_UPDATED', 'SYSTEM', 'Data updated in T24/CDH/MAHI/Unnati. Request completed and an SMS is sent to the customer.', NULL, 1),
  ('QUEUE', 'APZCBO', 'T24UPDATE', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'CHT', 'T24PENDING', 'T24_PENDING', 'SYSTEM', 'No or failed T24 response. Request moves to the T24 Pending queue.', NULL, 2),
  ('NEXT', 'APZCBO', 'T24PENDING', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'COMPLETED', 'T24_UPDATED', 'SYSTEM', 'Scheduler retry of T24 succeeds. Request completed.', NULL, 1),
  ('QUEUE', 'APZCBO', 'T24PENDING', 'CMSYSTEM', CURRENT_TIMESTAMP, 'SYSTEM', 'SYSTEM', 'T24PENDING', 'T24_RETRY', 'SYSTEM', 'Scheduler retry of T24 fails. Request stays in the T24 Pending queue.', NULL, 2),
  ('CRTAPPROVE', 'APZCBO', 'CRTQUEUE', 'CMCRT', CURRENT_TIMESTAMP, 'CRT', 'SYSTEM', 'T24UPDATE', 'CRT_APPROVED', 'CRT', 'CRT approves the CB-fail case. Request moves to T24 updation.', NULL, 1),
  ('REJECT', 'APZCBO', 'CRTQUEUE', 'CMCRT', CURRENT_TIMESTAMP, 'CRT', 'CRT', 'CRTREJECTED', 'CRT_REJECTED', 'CRT', 'CRT rejects the request. Request moves to the Rejected queue.', NULL, 2),
  ('APPROVED', 'APZCBO', 'INSQUEUE', 'CMINSURANCE', CURRENT_TIMESTAMP, 'INSURANCE', 'SYSTEM', 'T24UPDATE', 'INSURANCE_APPROVED', 'INSURANCE', 'Insurance team approves the Widowed -> Married change. Request moves to T24 updation.', NULL, 1),
  ('REJECT', 'APZCBO', 'INSQUEUE', 'CMINSURANCE', CURRENT_TIMESTAMP, 'INSURANCE', 'INSURANCE', 'INSREJECTED', 'INSURANCE_REJECTED', 'INSURANCE', 'Insurance team rejects. Request moves to the Rejected queue.', NULL, 2),
  ('RETRIGGER', 'APZCBO', 'T24PENDING', 'CMCHT', CURRENT_TIMESTAMP, 'CHT', 'SYSTEM', 'T24UPDATE', 'T24_RETRIGGERED', 'CHT', 'CHT user manually re-triggers T24 updation (single, multiple selection or bulk upload).', NULL, 1),
  ('VERIFY', 'APZCBO', 'COMPLETED', 'CMRPCTL', CURRENT_TIMESTAMP, 'RPCTL', 'RPCTL', 'TLVERIFIED', 'TL_VERIFIED', 'RPCTL', 'RPC TL sample check (5-10%) of completed cases. Marked as Verified with remarks.', NULL, 1),
  ('RECOMMEND', 'APZCBO', 'COMPLETED', 'CMRPCTL', CURRENT_TIMESTAMP, 'RPCTL', 'BST', 'BSTQUEUE', 'BST_RECOMMENDED', 'RPCTL', 'RPC TL recommends the case for BST review.', NULL, 2),
  ('VERIFY', 'APZCBO', 'COMPLETED', 'CMRPCHO', CURRENT_TIMESTAMP, 'RPCHO', 'RPCHO', 'RPCHOVERIFIED', 'RPCHO_VERIFIED', 'RPCHO', 'RPC HO sample check (5-10%, configurable) of RPC-cleared and Green channel cases. Marked as Verified with remarks.', NULL, 1),
  ('RECOMMEND', 'APZCBO', 'COMPLETED', 'CMRPCHO', CURRENT_TIMESTAMP, 'RPCHO', 'BST', 'BSTQUEUE', 'BST_RECOMMENDED', 'RPCHO', 'RPC HO recommends the case for BST review with remarks. The case appears in the BST report.', NULL, 2),
  ('VERIFY', 'APZCBO', 'BSTQUEUE', 'CMBST', CURRENT_TIMESTAMP, 'BST', 'BST', 'BSTVERIFIED', 'BST_VERIFIED', 'BST', 'BST user verifies the sample case and adds comments.', NULL, 1);

COMMIT;
