apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "appzillon-cm.fullname" . }}-config
  labels:
    {{- include "appzillon-cm.labels" . | nindent 4 }}
data:
  SPRING_PROFILES_ACTIVE: {{ .Values.env.SPRING_PROFILES_ACTIVE | quote }}
  SERVER_PORT: {{ .Values.env.SERVER_PORT | quote }}
  SERVER_SERVLET_CONTEXT_PATH: {{ .Values.env.SERVER_SERVLET_CONTEXT_PATH | quote }}
  JAVA_OPTS: {{ .Values.env.JAVA_OPTS | quote }}
