apiVersion: v1
kind: Secret
metadata:
  name: {{ include "appzillon-cm.fullname" . }}-secret
  labels:
    {{- include "appzillon-cm.labels" . | nindent 4 }}
type: Opaque
stringData:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.database.host }}:{{ .Values.database.port }}/{{ .Values.database.name }}"
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
  CDH_DATASOURCE_URL: "jdbc:postgresql://{{ .Values.cdhDatabase.host }}:{{ .Values.cdhDatabase.port }}/{{ .Values.cdhDatabase.name }}"
  CDH_DATASOURCE_USERNAME: {{ .Values.cdhDatabase.username | quote }}
  CDH_DATASOURCE_PASSWORD: {{ .Values.cdhDatabase.password | quote }}
