spring.main.allow-bean-definition-overriding=true
server.port=9286
server.context.path=/appzillonbankingloan
management.endpoints.web.exposure.include=*
spring.codec.max-in-memory-size=16
#-------------------------------------------
#BEGIN HIKARI POOL CONFIG1
#-------------------------------------------


# --- JDBC ---
spring.datasource.url = jdbc:postgresql://172.16.9.23:5455/grameenkoota
spring.datasource.username=cagl
spring.datasource.password=tHXS7TKtxwjAHHxFEc2PBHoHqzBoltGEX73HucqbWkfctg5GLPMrMx4369rsYnPh
spring.datasource.driverClassName=org.postgresql.Driver

# --- Hikari ---
spring.datasource.hikari.pool-name=LOAN-POSTGRE-GRAMEEN
spring.datasource.hikari.maximum-pool-size=100
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.keepalive-time=300000
spring.datasource.hikari.leak-detection-threshold=60000

# --- JPA / Hibernate (Boot + vendor map) ---
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database=POSTGRESQL
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl



-------------------------------------------
#BEGIN HIKARI POOL CONFIG2
#-------------------------------------------
# --- JDBC ---
apz.datasource.url = jdbc:postgresql://172.16.9.23:5455/grameenkoota
apz.datasource.username = cagl
apz.datasource.password = tHXS7TKtxwjAHHxFEc2PBHoHqzBoltGEX73HucqbWkfctg5GLPMrMx4369rsYnPh
apz.datasource.driverClassName = org.postgresql.Driver

# --- Hikari ---

apz.jpa.properties.hibernateDialect=org.hibernate.dialect.PostgreSQLDialect
apz.jpa.properties.ddlAuto=none
apz.jpa.properties.showSQL=true
apz.jpa.properties.formatSQL=true
apz.datasource.maximumPoolSize=20
apz.datasource.minimumIdle=5
apz.datasource.poolName=LOAN-POSTGRE-APPZILLONCB
apz.datasource.idleTimeOut=20000
apz.datasource.maxLifeTime=150000
#------------------------------------------------
#Logging
#--------------------------------------------------
logging.level.com.iexceed.appzillonbanking.cagl.*=DEBUG
logging.file.name=/app/logs/loan.log
logging.logback.rollingpolicy.file-name-pattern=/app/logs/loan-%d{yyyy-MM-dd}.%i.log
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=200
logging.logback.rollingpolicy.clean-history-on-start=false
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

ab.common.interFaceJSONDir=/app/resources/intfJSON/
ab.common.externalServiceURLPath=/app/properties/ExternalServiceURL-${spring.profiles.active}.json
ab.common.reportsTemplateDir=/app/reports/
ab.common.reportsOutputDir=/app/report_output/sanction

#ab.common.interFaceJSONDir=D:/GRAMMIN\ KOTA/CAGL/gk-unified-app/BACKEND/Micro-Services/CAGL_PROJECT_MICROSERVICES/Interfaces/
#ab.common.externalServiceURLPath=D:/GRAMMIN\ KOTA/CAGL/gk-unified-app/BACKEND/Micro-Services/CAGL_PROJECT_MICROSERVICES/Interfaces/ExternalServiceURL.json
#ab.common.reportsTemplateDir=D:/GRAMMIN\ KOTA/CAGL/gk-unified-app/BACKEND/Micro-Services/CAGL_PROJECT_MICROSERVICES/Reports/
#ab.common.reportsOutputDir=D:/GRAMMIN\ KOTA/CAGL/ReportsOuput/Sanction

ab.common.numOfRecordsInWidget=25
ab.common.numOfDaysRecords=25
ab.common.accountSTP=Y
ab.common.depositSTP=N
ab.common.cardSTP=N
ab.common.loanSTP=N

litFilePath=/app/properties/COB_LITCODES_
cobFlags=/app/properties/COB_FLAGS.properties
litFileFormat=csv
litCodeFilePath=/app/resources/ONBOARDING_
