spring.main.allow-bean-definition-overriding=true

#spring.datasource.hikari.pool-name= CAGL-APZBANKING


#externalPropFile.path=$HOME/application-properties/application.properties
#dbProperties.path=$HOME/database-properties/database.properties

server.port=9296
server.context.path=/appzillonbankingcm
management.endpoints.web.exposure.include=*
spring.codec.max-in-memory-size=16
#-------------------------------------------
#BEGIN HIKARI POOL CONFIG1 (PostgreSQL - Primary tb_cm_*)
#-------------------------------------------
spring.datasource.url = jdbc:postgresql://172.16.4.81:5433/grameenkoota_pt
spring.datasource.username=cagl
spring.datasource.password=JF+tY/d0To73UXl73VdyzNllv70BSfzhCQGvCu7FjVqSfyVQ4OyClTYAL/ex4gkR
spring.datasource.driverClassName=org.postgresql.Driver
#spring.datasource.maximum-pool-size=50
#spring.datasource.minimum-idle=5
#-------------------------------------------
#BEGIN HIKARI POOL CONFIG2 (CDH MySQL - Central Data Hub)
#-------------------------------------------
cdh.datasource.url = jdbc:mysql://172.16.108.10:4402/unifiedapp_test
cdh.datasource.username = unifieduat
cdh.datasource.password = OSG44FfxHSGsqcO7RDm0mAu4PIRjnzg+cP4r4N2ROsutkFXEG8Qp0FDc8c0qhipC
cdh.datasource.driverClassName = com.mysql.cj.jdbc.Driver

#-------------------------------------------
#-------------------------------------------
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.database=POSTGRESQL
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
#----------------------------------------------
spring.jpa.properties.hibernateDialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.ddlAuto=none
spring.jpa.properties.showSQL=true
spring.jpa.properties.formatSQL=true
spring.datasource.maximumPoolSize=500
spring.datasource.minimumIdle=10
spring.datasource.poolName=CM-POSTGRE-GRAMEEN
spring.datasource.idleTimeOut=30000
spring.datasource.maxLifeTime=150000

cdh.jpa.properties.hibernateDialect=org.hibernate.dialect.MySQL8Dialect
cdh.jpa.properties.ddlAuto=none
cdh.jpa.properties.showSQL=false
cdh.jpa.properties.formatSQL=false
cdh.datasource.maximumPoolSize=20
cdh.datasource.minimumIdle=2
cdh.datasource.poolName=CM-MYSQL-CDH
cdh.datasource.idleTimeOut=30000
cdh.datasource.maxLifeTime=150000
#------------------------------------------------
#Logging
#--------------------------------------------------
logging.level.com.iexceed.appzillonbanking.cagl.*=ERROR
logging.file.name=/app/logs/cm.log
logging.logback.rollingpolicy.file-name-pattern=/app/logs/cm-%d{yyyy-MM-dd}.%i.log
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=200
logging.logback.rollingpolicy.clean-history-on-start=false
logging.level.com.zaxxer.hikari.HikariConfig=DEBUG

ab.common.interFaceJSONDir=/app/resources/intfJSON/
ab.common.externalServiceURLPath=/app/properties/ExternalServiceURL-${spring.profiles.active}.json

# Downstream Microservices
url.kyc.service=http://apz-ms-appzillonbanking-kyc:9287/appzillonbankingkyc
url.dms.service=http://apz-ms-appzillonbanking-document:9287/appzillonbankingdocument
url.cbs.service=http://apz-ms-appzillonbanking-cbs:9288/appzillonbankingcbs
url.kendra.service=http://apz-ms-appzillonbanking-kendra:9290/appzillonbankingkendra
