spring.main.allow-bean-definition-overriding=true

spring.datasource.hikari.pool-name= CAGL-APZBANKING

#externalPropFile.path=$HOME/application-properties/application.properties
#dbProperties.path=$HOME/database-properties/database.properties
server.port=9293
server.servlet.context-path=/appzillonbankingcob
management.endpoints.web.exposure.include=*
spring.codec.max-in-memory-size=16
#-------------------------------------------
#BEGIN HIKARI POOL CONFIG1
#-------------------------------------------
spring.datasource.url = jdbc:postgresql://192.168.2.47:5432/grameenkoota
spring.datasource.username=grameenkoota
spring.datasource.password=grameenkoota
spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.properties.hibernateDialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.ddlAuto=none
spring.jpa.properties.showSQL=true
spring.jpa.properties.formatSQL=true
spring.datasource.maximumPoolSize=5
spring.datasource.minimumIdle=2
spring.datasource.poolName=CAGL-POSTGRE-GRAMEEN
spring.datasource.idleTimeOut=30000
spring.datasource.maxLifeTime=30000
#-------------------------------------------
#BEGIN HIKARI POOL CONFIG2
#-------------------------------------------
apz.datasource.url = jdbc:postgresql://192.168.2.47:5432/grameenkoota
apz.datasource.username = grameenkoota
apz.datasource.password = grameenkoota
apz.datasource.driverClassName = org.postgresql.Driver

apz.jpa.properties.hibernateDialect=org.hibernate.dialect.PostgreSQLDialect
apz.jpa.properties.ddlAuto=none
apz.jpa.properties.showSQL=true
apz.jpa.properties.formatSQL=true
apz.datasource.maximumPoolSize=5
apz.datasource.minimumIdle=2
apz.datasource.poolName=CAGL-POSTGRE-APPZILLONCB
apz.datasource.idleTimeOut=30000
apz.datasource.maxLifeTime=30000
#-------------------------------------------
#-------------------------------------------
spring.jpa.properties.hibernate.format_sql=false
#----------------------------------------------
#------------------------------------------------
#Logging
#--------------------------------------------------
logging.level.com.iexceed.appzillonbanking.cagl.*=DEBUG
logging.file.name=/opt/cob/logs/cob.log
logging.logback.rollingpolicy.file-name-pattern=/opt/cob/logs/cob-%d{yyyy-MM-dd}.%i.log
logging.pattern.file= "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=200
logging.logback.rollingpolicy.clean-history-on-start=false

#logging.level.org.hibernate.SQL=DEBUG
#logging.level.com.zaxxer.hikari.HikariConfig=DEBUG
#logging.level.com.zaxxer.hikari=TRACE

ab.common.interFaceJSONDir=/opt/cob/interfaces/
ab.common.externalServiceURLPath=/opt/cob/ExternalServiceURL.json
ab.common.fileUploadPath=/opt/cob/FileUpload/
#ab.common.interFaceJSONDir=D:/CAGL/Local/interfaces/
#ab.common.externalServiceURLPath=D:/CAGL/Local/ExternalServiceURL.json
#ab.common.fileUploadPath=D:/CAGL/Local/FileUpload/
ab.common.qrWidth=300
ab.common.qrHeight=300

# ===========================================
# Dashboard Configuration
# ===========================================
cob.dashboard.tablet.page-size=10
cob.dashboard.web.page-size=30

# ============================================
# BMReinterview config
# ============================================
onboarding.BMReinterview.default-kt-question-count=5
onboarding.BMReinterview.max-kendra-distance=500

# =============================================
# GRTService config
# =============================================
onboarding.GRTService.house-visit-minimum-percentage=50
onboarding.GRTService.minimum-grt-members=5

# =============================================
# CGTService config
# =============================================
onboarding.CGTService.cgt-mandatory-days=3
onboarding.CGTService.cgt-minimum-members=5

# =============================================
# KendraGroupDissolutionService config
# =============================================
ab.common.groupDissolutionDays=90
ab.common.kendraDissolutionDays=90

STATIC_LOAN_AMOUNT=40000
STATIC_LOAN_FREQUENCY=Weekly
STATIC_LOAN_TERM=104
STATIC_LOAN_PRODUCT_ID=GL.IGL.PRAGATI.PLUS
STATIC_LOAN_MEMBER_INS = Y
STATIC_LOAN_SPOUSE_INS = Y
STATIC_LOAN_MEMBER_INS_AMOUNT = 400
STATIC_LOAN_SPOUSE_INS_AMOUNT = 1040
STATIC_LOAN_PRODUCT_TYPE=GL IGL PRAGATI PLUS

# Record Lock Configuration
record.lock.rpc.role=RPC
record.lock.rpc.inactivity-minutes=60

#AMLBRE static data
onboarding.aml.product=Micro Loan
onboarding.aml.customerType=GL
onboarding.aml.reason=AML Check

#Password for video List
cag.login.password=Cag@2026
